version: 0.2
variables:
  DOCKER_USER: satishkollati
  DOCKER_PASS: dckr_pat__50E-XDAUca2Pr5pSmq0srKYumg
  APP_NAME: my-web-ap
phases:
 pre_build:
  commands:
     - echo "$DOCKER_PASS" | docker login -u ${DOCKER_USER} --password-stdin
 build:
    commands:
      - docker build -t ${APP_NAME} .
 post_build:
    command:
      - docker tag ${APP_NAME}  ${DOCKER_USER}/${APP_NAME}
      - docker push  ${DOCKER_USER}/${APP_NAME}
