name: Create New Feature Branch with Specific Changes

on:
  push:
    branches:
      - FSB  # Trigger workflow when code is pushed to the FSB branch

jobs:
  create-branch:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the FSB branch
      - name: Checkout FSB branch
        uses: actions/checkout@v4
        with:
          ref: FSB

      # Step 2: Set up Git user identity
      - name: Set up Git user
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@example.com"

      # Step 3: Generate a unique branch name
      - name: Generate a unique branch name
        id: branch_na
