name: Create dynamic branch and copy files

on:
  workflow_dispatch:
    inputs:
      files_to_copy:
        description: 'List of files or folders to copy (comma-separated)'
        required: true

jobs:
  create-branch:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Set up Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    - name: Get current branch name
      id: get_branch
      run: |
        BASE_BRANCH=$(git rev-parse --abbrev-ref HEAD)  # Get the current branch name
        echo "BASE_BRANCH=$BASE_BRANCH" >> $GITHUB_ENV  # Export the base branch name to environment variable
        echo "Current base branch is: $BASE_BRANCH"

    - name: Generate dynamic branch name
      id: generate_branch
      run: |
        # Generate date and UUID suffix
        DATE_SUFFIX=$(date +%Y%m%d%H%M%S)  # Date format: YYYYMMDDHHMMSS
        UUID_SUFFIX=$(uuidgen)  # Generate a UUID
        DYNAMIC_SUFFIX="${DATE_SUFFIX}-${UUID_SUFFIX}"
        
        # Create the new branch name by combining the base branch with the dynamic suffix
        NEW_BRANCH="${BASE_BRANCH}-${DYNAMIC_SUFFIX}"
        echo "NEW_BRANCH=$NEW_BRANCH" >> $GITHUB_ENV  # Export the new branch name
        echo "Generated new branch name: $NEW_BRANCH"

    - name: Create new branch
      run: |
        git checkout -b $NEW_BRANCH  # Create a new branch from the current branch
  

    - name: Commit changes
      run: |
        git add .
        git commit -m "Add specified files to $NEW_BRANCH"

    - name: Push the new branch
      run: |
        git push origin $NEW_BRANCH
