name: Copy Files or Directories from Input Branch

on:
  workflow_dispatch:
    inputs:
      source_branch:
        description: "Source branch to copy files or directories from"
        required: true
        default: "copybranch"
      source_paths:
        description: "Comma-separated list of files or directories in the source branch"
        required: true
        default: "src,file1.txt,dir1"
      target_path:
        description: "Target path for the copied files or directories"
        required: true
        default: "target"

jobs:
  copy-files:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the source branch
      - name: Checkout Source Branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.source_branch }}

      # Step 2: Create target directory
      - name: Create Target Directory
        run: mkdir -p ${{ github.event.inputs.target_path }}

      # Step 3: Copy multiple files or directories
      - name: Copy Files or Directories
        run: |
          # Convert the comma-separated list to an array
          IFS=',' read -r -a source_paths <<< "${{ github.event.inputs.source_paths }}"
          
          # Loop through the paths and copy files or directories
          for source_path in "${source_paths[@]}"; do
            if [ -f "$source_path" ]; then
              # Input is a file
              echo "Copying file: $source_path"
              cp "$source_path" ${{ github.event.inputs.target_path }}
            elif [ -d "$source_path" ]; then
              # Input is a directory
              echo "Copying directory: $source_path"
              cp -r "$source_path" ${{ github.event.inputs.target_path }}
            else
              echo "The specified source path $source_path does not exist."
              exit 1
            fi
          done

      # Step 4: Verify copied files or directories
      - name: Verify Target Path Contents
        run: ls -la ${{ github.event.inputs.target_path }}
