name: Copy Files or Directory from Input Branch

on:
  workflow_dispatch:
    inputs:
      source_branch:
        description: "Source branch to copy files or directory from"
        required: true
        default: "develop"
      source_path:
        description: "Path to a file or directory in the source branch"
        required: true
        default: "src"
      target_path:
        description: "Target path for the copied files or directory"
        required: true
        default: "target"

jobs:
  copy-files:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the source branch
      - name: Checkout Source Branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.source_branch }}

      # Step 2: Create target directory
      - name: Create Target Directory
        run: mkdir -p ${{ github.event.inputs.target_path }}

      # Step 3: Copy files or directory dynamically
      - name: Copy File or Directory
        run: |
          if [ -f "${{ github.event.inputs.source_path }}" ]; then
            # Input is a file
            cp "${{ github.event.inputs.source_path }}" ${{ github.event.inputs.target_path }}
          elif [ -d "${{ github.event.inputs.source_path }}" ]; then
            # Input is a directory
            cp -r "${{ github.event.inputs.source_path }}"/* ${{ github.event.inputs.target_path }}
          else
            echo "The specified source path does not exist."
            exit 1
          fi

      # Step 4: Verify copied files or directory
      - name: Verify Target Path Contents
        run: ls -la ${{ github.event.inputs.target_path }}
