name: build and upload artifact
on:
 workflow_dispatch:
  inputs:
    java_version:
      type: string
      required: true
      default: '17'
env:
 build: target
jobs:
  Build:
    runs-on: ubuntu-22.04
    steps:
       - name: clone the repo
         uses: actions/checkout@v4
       - name: install Java
         uses: actions/setup-java@v4
         with:
            java-version: ${{ inputs.java_version }}
            distribution: 'temurin'
       - name: Build the code
         run: mvn clean package

       - name: Upload Artifact Example
         uses: actions/upload-artifact@v3
         with:
          name: Build-artifact
          path: ${{env.build}}/*.war
  deploy:
    needs: Build
    runs-on: windows-latest
    steps:
     - name: Download the artifact
       uses: actions/download-artifact@v3
       with:
          name: Build-artifact 

     - name: List files to confirm download
       run: |
          dir


      
